### ISSUE TITLE
Errors After Taking First Photo

### ISSUE THREAD

**Issue by emiliodacosta** [vinissimus/opencv-js-webworker#20]
First off, thank you for providing this demo / example code!

I'm currently encountering the following errors after I successfully take the photo from the video:

```
cv.js:38` Uncaught TypeError: Cannot read properties of undefined (reading 'msg')
    at worker.onerror (cv.js:38:55)
worker.onerror @ cv.js:38
error (async)
load @ cv.js:38
onClick @ page.js:25
callCallback @ react-dom.development.js:20565
invokeGuardedCallbackImpl @ react-dom.development.js:20614
invokeGuardedCallback @ react-dom.development.js:20689
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:20703
executeDispatch @ react-dom.development.js:32128
processDispatchQueueItemsInOrder @ react-dom.development.js:32160
processDispatchQueue @ react-dom.development.js:32173
dispatchEventsForPlugins @ react-dom.development.js:32184
eval @ react-dom.development.js:32374
batchedUpdates$1 @ react-dom.development.js:24953
batchedUpdates @ react-dom.development.js:28844
dispatchEventForPluginEventSystem @ react-dom.development.js:32373
dispatchEvent @ react-dom.development.js:30141
dispatchDiscreteEvent @ react-dom.development.js:30112


cv.worker.js:80 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/js/opencv_3_4_custom_O3.js' failed to load.
    at onmessage (http://localhost:3000/js/cv.worker.js:80:12)
onmessage @ cv.worker.js:80

lockdown-install.js:1 null
```

It's not a total crash as the video component continues rendering. However, the 'Processing' text never reverts back to 'Take a photo' and I can't take any more photos.

![Screenshot 2024-04-23 at 6 40 28 PM](https://github.com/vinissimus/opencv-js-webworker/assets/27406699/0d68ff36-a453-489a-9436-717ab375ca9f)

Source code:
https://github.com/emiliodacosta/openCvJs

**Comment by aralroca** [comment]
Are you tried this example https://vinissimus.github.io/opencv-js-webworker/ ? or locally? 🤔

**Comment by emiliodacosta** [comment]
Functionality is working fine at the url you just shared. I'm experiencing the issue locally.

So far, I'm thinking it could be related to the following:
https://stackoverflow.com/questions/57481062/web-worker-importscripts-domexception-script-failed-to-load

https://developer.chrome.com/blog/tweeks-to-addAll-importScripts/

**Comment by emiliodacosta** [comment]
This is a separate issue so perhaps I should be creating a new thread, but...

If I try to fork your repo, npm install, npm run dev, I get the following error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/emidac/Documents/code/encodeAI/finalProject/vinissimus/opencv-js-webworker/node_modules/next/dist/compiled/babel-loader/index.js:1:3586 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Separately, if you want to reproduce the errors from the OP, fork my repo here:
https://github.com/emiliodacosta/openCvJs

**Comment by emiliodacosta** [comment]
Here's my repo where I'm experiencing the errors from the OP:

https://github.com/emiliodacosta/openCvJs

**Comment by emiliodacosta** [comment]
I got my local repo working and figured out why there was an issue... I didn't have the file `./opencv_3_4_custom_O3.js` because I initially followed the instructions from your blog post (https://aralroca.com/blog/opencv-in-the-web) but then the code I copied later from this repo was trying to import that file.

A new question though... when I try the following:
`self.importScripts('./opencv.js')`
I no longer get an error immediately, but I get the same outcome of 1 photo taken and then being stuck in 'Processing...' and then ~20-30 seconds later, I get the following errors:
```
cv.js:38 Uncaught TypeError: Cannot read properties of undefined (reading 'msg')
    at worker.onerror (cv.js:38:55)
worker.onerror @ cv.js:38
error (async)
load @ cv.js:38
onClick @ page.js:25
callCallback @ react-dom.development.js:20565
invokeGuardedCallbackImpl @ react-dom.development.js:20614
invokeGuardedCallback @ react-dom.development.js:20689
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:20703
executeDispatch @ react-dom.development.js:32128
processDispatchQueueItemsInOrder @ react-dom.development.js:32160
processDispatchQueue @ react-dom.development.js:32173
dispatchEventsForPlugins @ react-dom.development.js:32184
eval @ react-dom.development.js:32374
batchedUpdates$1 @ react-dom.development.js:24953
batchedUpdates @ react-dom.development.js:28844
dispatchEventForPluginEventSystem @ react-dom.development.js:32373
dispatchEvent @ react-dom.development.js:30141
dispatchDiscreteEvent @ react-dom.development.js:30112

cv.worker.js:83 Uncaught Error: Error on loading OpenCV
    at cv.worker.js:83:20
    at cv.worker.js:64:14
(anonymous) @ cv.worker.js:83
(anonymous) @ cv.worker.js:64
setInterval (async)
waitForOpencv @ cv.worker.js:60
onmessage @ cv.worker.js:81

lockdown-install.js:1 null
```

![Screenshot 2024-04-23 at 10 54 37 PM](https://github.com/vinissimus/opencv-js-webworker/assets/27406699/b9712697-13f6-42b5-964d-f521c06e6e60)

**Comment by emiliodacosta** [comment]
Since it seems that `opencv_3_4_custom_O3.js` is the working one being used, is there a special reason that you still have `opencv.js` and `opencv_3_4_custom_Oz.js` in the `public/js` folder as well?
